# Generated by Django 4.1.4 on 2022-12-15 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20190310_1527'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='restaurant',
    #         name='taste',
    #     ),
    #     migrations.RemoveField(
    #         model_name='restaurant',
    #         name='vat',
    #     ),
    # ]
