# Generated by Django 4.1.4 on 2022-12-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_remove_restaurant_taste_remove_restaurant_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(choices=[(1, 'Koyambedu'), (2, 'Nungambakkam'), (3, 'Anna Nagar'), (4, 'Adyar'), (5, 'Besant Nagar'), (6, 'Avadi'), (7, 'Mylapore'), (8, 'R.A Puram'), (9, 'Kotturpuram'), (10, 'Thiruvanmiyur')], max_length=120),
        ),
    ]
