# Generated by Django 4.1.4 on 2022-12-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_alter_restaurant_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(choices=[('Koyambedu', 'Koyambedu'), ('Nungambakkam', 'Nungambakkam'), ('Anna Nagar', 'Anna Nagar'), ('Adyar', 'Adyar'), ('Besant Nagar', 'Besant Nagar'), ('Avadi', 'Avadi'), ('Mylapore', 'Mylapore'), ('R.A Puram', 'R.A Puram'), ('Kotturpuram', 'Kotturpuram'), ('Thiruvanmiyur', 'Thiruvanmiyur')], max_length=120),
        ),
    ]
